### ISSUE TITLE
Causes Error Lags the game coop/solo

### ISSUE THREAD

**Issue by Dreifonz** [zolantris/ValheimMods#36]
### What happened?

![image (3)](https://github.com/zolantris/ValheimMods/assets/120353626/2d66b5e2-aa05-48d3-86ab-76015f224d1a)
![image (4)](https://github.com/zolantris/ValheimMods/assets/120353626/df726ac4-5ca1-47ea-a6b9-d51578a664ab)

 Produced these errors upon updating the mod from 1.6.7 to 1.6.8

### Environment

```markdown
OS:
- **OS**: Windows 10 | Ubuntu 20.04
- **Graphics**: DX11 (or Vulkan)
Mods:
- **BepInEx**: 5.4.2202
- Jotunn 2.15.2
- **ValheimRAFT**: 1.6.8
```

**Comment by dominik199818** [comment]
he dont even test this i think XD

**Comment by dominik199818** [comment]
and there is no way of deleting this error, version downgrade dont work, deleting mod dont work

**Comment by Saatvik-Aggarwal** [comment]
This error seems to be there for 1.6.7 and 1.6.8, but downgrading back to 1.6.6 made it go away.

**Comment by zolantris** [comment]
Mods that patched the class most likely caused this the MoveableBaseRootComponent was renamed causing mods that relied on this reference to fail. 

1.6.9 and onwards restored the naming structure. So this should be considered resolved.

---- 

And yes I did test this on an isolated server without many mod. I also removed plan build since I was testing having without it since there were a few problems with not using it. 

Plan build has patches for valheim raft so it would cause this issue if it directly reference a class. Did not test having plan build back nor whatever other mods cause regressions by overriding valheimraft.
