### ISSUE TITLE
ValheimRAFT crashing games, tanking performance, 1.6.8 version

### ISSUE THREAD

**Issue by MeowXeno** [zolantris/ValheimMods#37]
### What happened?

Upon updating ValheimRAFT to 1.6.8 we cannot place longships/karve/rafts of any kind, it tanks our performance from 120-180fps to single digits upon rendering ANY ship, be it placed or a raft already created, the bepinex logs show red text involving object placement, then crashes the host and game entirely,

### Steps to reproduce

install 1.6.8

place any ship

game crash

### Environment

```markdown
OS:
- **OS**: Windows 11 | Ubuntu 20.04
- **Graphics**: DX11 (or Vulkan)
Mods:
- **BepInEx**: 5.4.2202
- Jotunn 2.15.2
- **ValheimRAFT**: 1.6.8
```

**Comment by dominik199818** [comment]
this retard broke this mod and also a lot of savegames... hope he repair it fast. IT's last time im using this mod

**Comment by dominik199818** [comment]
even deleting mod, backups, nothing help if u have placed something of this mod in world. new game will help

**Comment by zolantris** [comment]
You can downgrade the mod if there are problems. Patch versions do not break critical functionality so I'm confused how backups of older versions of this mkd did not fix things.

There were problems with store deploys on 1.6.7 due to a request to make manual installs easier it regressed thunderstore auto installs.
 
1.6.8 had typos renamed to class's which I did not know were being accessed and patched by other libraries. That caused most of the errors reported yesterday.

Errors like this are usually related to unforseen problems like mods patching or interacting with valheimraft outside of the core code.

**On that note, I will be keeping releases to only weekly updates since it's hard for people to manually install or fix things. There are now a few volunteers for testing betas.**
